dependencies {
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutine}")
    api("com.badlogicgames.gdx:gdx:${Versions.gdx}")
    api("com.badlogicgames.ashley:ashley:${Versions.ashley}")
    api("io.github.libktx:ktx-actors:${Versions.ktx}")
    api("io.github.libktx:ktx-app:${Versions.ktx}")
    api("io.github.libktx:ktx-assets-async:${Versions.ktx}")
    api("io.github.libktx:ktx-ashley:${Versions.ktx}")
    api("io.github.libktx:ktx-collections:${Versions.ktx}")
    api("io.github.libktx:ktx-graphics:${Versions.ktx}")
    api("io.github.libktx:ktx-log:${Versions.ktx}")
    api("io.github.libktx:ktx-math:${Versions.ktx}")
    api("io.github.libktx:ktx-preferences:${Versions.ktx}")
    api("io.github.libktx:ktx-scene2d:${Versions.ktx}")
    api("io.github.libktx:ktx-style:${Versions.ktx}")
}
